import { FormField } from '@/types/common/FormField';
import { TableHead } from '@/types/common/TableHead';
import { ProductDto } from '@/types/product/product.type';

export const formSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Description',
    labelVisibility: 'visible',
    fieldName: 'description',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Price',
    labelVisibility: 'visible',
    fieldName: 'price',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Stock',
    labelVisibility: 'visible',
    fieldName: 'stock',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
  {
    column: 12,
    align: 'default',
    label: 'Files',
    labelVisibility: 'visible',
    fieldName: 'images',
    dataType: 'file',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: false,
  },
];

export const formViewSchema: FormField[] = [
  {
    column: 12,
    align: 'default',
    label: 'Name',
    labelVisibility: 'visible',
    fieldName: 'name',
    dataType: 'text',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 12,
    align: 'default',
    label: 'Description',
    labelVisibility: 'visible',
    fieldName: 'description',
    dataType: 'textarea',
    action: null,
    defaultValue: '',
    isEnum: false,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'price',
    labelVisibility: 'visible',
    fieldName: 'price',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Stock',
    labelVisibility: 'visible',
    fieldName: 'stock',
    dataType: 'number',
    action: null,
    defaultValue: '',
    isEnum: true,
    enum: [],
    isRequired: true,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
  {
    column: 4,
    align: 'default',
    label: 'Thumbails',
    labelVisibility: 'visible',
    fieldName: 'images',
    dataType: 'image',
    action: null,
    defaultValue: [],
    isEnum: false,
    enum: [],
    isRequired: false,
    showWhen: null,
    onChange: null,
    disabled: true,
  },
];

export const tableSchema: TableHead<ProductDto>[] = [
  {
    label: 'Name',
    accessor: 'name',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Description',
    accessor: 'description',
    sortable: true,
    searchable: true,
    align: 'start',
  },
  {
    label: 'Price',
    accessor: 'price',
    sortable: true,
    searchable: false,
    align: 'end',
  },
];
